#!/usr/bin/env bash
# av-bridge collector enrolment bootstrap.
#
# Invoked as:
#   curl -fsSL <portal>/public/collectors/install.sh | sudo AV_ENROLL_TOKEN=<token> bash
#
# The portal generates a per-collector one-liner in the /collectors page.
# This script:
#   1. Sanity-checks environment (root, curl, systemd, target OS).
#   2. Redeems AV_ENROLL_TOKEN against the cloud → gets HMAC secret + IDs.
#   3. Ensures the av-bridge binary is present (optional download hook).
#   4. Writes /etc/av-bridge/env and /etc/av-bridge/config.yaml with the
#      minimum config the bridge needs to boot; devices come from the
#      cloud config-pull endpoint (/bridge/config) on first heartbeat.
#   5. Installs the systemd unit, starts av-bridge, waits for healthz.
#
# Idempotent: re-running with the same token fails at step 2 (token is
# single-use) — that's intentional. If enrolment already succeeded and
# only the service needs restarting, use `systemctl restart av-bridge`.
set -euo pipefail

CLOUD_BASE_URL="${CLOUD_BASE_URL:-@@CLOUD_BASE_URL@@}"
ENROLL_ENDPOINT="${CLOUD_BASE_URL}/public/collectors/enroll"

CONFIG_DIR="/etc/av-bridge"
ENV_FILE="${CONFIG_DIR}/env"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
SERVICE_USER="av-bridge"
SERVICE_FILE="/etc/systemd/system/av-bridge.service"
BIN_PATH="/usr/local/bin/av-bridge"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

# ── Preflight ────────────────────────────────────────────────────────────────

[ "$(id -u)" -eq 0 ] || die "run as root (try: sudo AV_ENROLL_TOKEN=... bash -)"
[ -n "${AV_ENROLL_TOKEN:-}" ] || die "AV_ENROLL_TOKEN environment variable is required"
command -v curl >/dev/null 2>&1 || die "curl is required (apt install curl)"
command -v jq   >/dev/null 2>&1 || die "jq is required (apt install jq)"
command -v systemctl >/dev/null 2>&1 || die "systemctl is required (this script targets systemd hosts)"

HOSTNAME_TAG="$(hostname 2>/dev/null || echo unknown)"

# ── Redeem the token ─────────────────────────────────────────────────────────

echo "==> Redeeming enrollment token against ${ENROLL_ENDPOINT}"
REDEEM_JSON="$(mktemp)"
trap 'rm -f "$REDEEM_JSON"' EXIT

HTTP_CODE="$(curl -sS -o "$REDEEM_JSON" -w '%{http_code}' \
    -X POST "$ENROLL_ENDPOINT" \
    -H 'Content-Type: application/json' \
    --data-binary "$(jq -n --arg t "$AV_ENROLL_TOKEN" --arg h "$HOSTNAME_TAG" \
        '{token:$t, hostname:$h}')" \
    || true)"

if [ "$HTTP_CODE" != "200" ]; then
    ERR="$(jq -r '.error // "unknown error"' <"$REDEEM_JSON" 2>/dev/null || echo "unknown")"
    die "enrollment failed (HTTP $HTTP_CODE): $ERR"
fi

COLLECTOR_ID="$(jq -r '.collector_id'         <"$REDEEM_JSON")"
BRIDGE_ID="$(jq -r    '.bridge_collector_id'  <"$REDEEM_JSON")"
HMAC_SECRET="$(jq -r  '.hmac_secret'          <"$REDEEM_JSON")"
CLOUD_URL="$(jq -r    '.cloud_base_url'       <"$REDEEM_JSON")"
[ -n "$CLOUD_URL" ] && [ "$CLOUD_URL" != "null" ] || CLOUD_URL="$CLOUD_BASE_URL"

echo "    Enrolled as: $BRIDGE_ID (id=$COLLECTOR_ID)"

# ── Service user + directories ───────────────────────────────────────────────

if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi
mkdir -p "$CONFIG_DIR" /var/lib/av-bridge /var/log/av-bridge
chown "$SERVICE_USER:$SERVICE_USER" /var/lib/av-bridge /var/log/av-bridge
chown root:"$SERVICE_USER" "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"

# ── Binary ───────────────────────────────────────────────────────────────────

# For collector-enroll v1 we assume the binary has been placed at
# /usr/local/bin/av-bridge already (via a tarball, package, or Ansible
# role). A follow-up will teach this script to fetch signed releases
# from GitHub; the check below stays useful either way.
if [ ! -x "$BIN_PATH" ]; then
    if [ -n "${AV_BRIDGE_BINARY_URL:-}" ]; then
        echo "==> Downloading av-bridge from ${AV_BRIDGE_BINARY_URL}"
        curl -fsSL -o "$BIN_PATH" "$AV_BRIDGE_BINARY_URL"
        chmod 755 "$BIN_PATH"
    else
        die "$BIN_PATH not found. Install the av-bridge binary first
       (e.g. from the tarball produced by \`make dist\`), then re-run."
    fi
fi

# ── Config + env ─────────────────────────────────────────────────────────────

echo "==> Writing $ENV_FILE"
umask 077
cat >"$ENV_FILE" <<EOF
# av-bridge — generated by install.sh at enrollment time. Do not commit.
CLOUD_WEBHOOK_URL=${CLOUD_URL}/ingest
CLOUD_HMAC_SECRET=${HMAC_SECRET}
EOF
chown root:"$SERVICE_USER" "$ENV_FILE"
chmod 640 "$ENV_FILE"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "==> Writing $CONFIG_FILE"
    cat >"$CONFIG_FILE" <<EOF
# av-bridge — generated by install.sh. Device inventory pulls from the
# cloud on first heartbeat via /bridge/config. Edit here to override
# local listen address, poll intervals, etc.
hub:
  listen_addr: "0.0.0.0:8080"
  heartbeat_period: 30s
  log_level: info

cloud:
  webhook_url: "\${CLOUD_WEBHOOK_URL}"
  collector_id: "${BRIDGE_ID}"
  hmac_secret: "\${CLOUD_HMAC_SECRET}"
  portal_api: "${CLOUD_URL}"
  push_interval: 30s
  retry_attempts: 3
  retry_delay: 5s

devices: []
EOF
    chown root:"$SERVICE_USER" "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"
fi

# ── Systemd unit ─────────────────────────────────────────────────────────────

echo "==> Installing systemd unit"
cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=av-bridge (on-prem AV device gateway)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
EnvironmentFile=${ENV_FILE}
ExecStart=${BIN_PATH} -config ${CONFIG_FILE}
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/av-bridge /var/log/av-bridge

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now av-bridge

# ── Health check ─────────────────────────────────────────────────────────────

echo "==> Waiting for av-bridge to be healthy..."
for i in $(seq 1 30); do
    if curl -fsS -o /dev/null "http://127.0.0.1:8080/healthz" 2>/dev/null; then
        echo ""
        echo "===================================================="
        echo " av-bridge enrolled + running as $BRIDGE_ID"
        echo "===================================================="
        echo ""
        echo "  Next steps:"
        echo "  * The portal /collectors page will light up green"
        echo "    once the first heartbeat lands (~30 seconds)."
        echo "  * Add devices from the portal — the bridge pulls"
        echo "    config on each poll and reconciles automatically."
        echo "  * Logs: journalctl -u av-bridge -f"
        echo ""
        exit 0
    fi
    sleep 2
done

die "av-bridge failed to become healthy — check: journalctl -u av-bridge -e"
